spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod?useSSL=false
    username: recipe_prod_user
    password: fafik
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false